name: Build and Test Regnode

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: golang/1.22.3-alpine3.19
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Go program
        run: make all

      - name: Save Go program artifact
        uses: actions/upload-artifact@v4
        with:
          name: regnode
          path: build/*/regnode
          retention-days: 5
          overwrite: true
